version: 2
jobs:
  build_armhf:
    machine: true
    steps:
      - checkout

      - run:
          name: Run Shellcheck
          command: |
            make shellcheck

      - run:
          name: Create SD image
          command: |
            VERSION=${CIRCLE_TAG} BUILD_ARCH=armhf make sd-image

      - run:
          name: Prepare artifacts
          command: |
            mkdir -p output
            cp armhf/hypriotos* output/

      - store_artifacts:
          path: /home/circleci/project/output

      - deploy:
          name: Deploy
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              curl -sSL https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip -o ghr.zip
              unzip ghr.zip
              if [[ $CIRCLE_TAG = *"rc"* ]]; then
                pre=-prerelease
              fi
              ./ghr $pre -u hypriot $CIRCLE_TAG output/
            fi
  build_arm64: # Could not find a good way to do multiple arch builds, so it is a simple duplication.
    machine: true
    steps:
      - checkout

      - run:
          name: Run Shellcheck
          command: |
            make shellcheck

      - run:
          name: Create SD image
          command: |
            VERSION=${CIRCLE_TAG} BUILD_ARCH=arm64 make sd-image

      - run:
          name: Prepare artifacts
          command: |
            mkdir -p output
            cp arm64/hypriotos* output/

      - store_artifacts:
          path: /home/circleci/project/output

      - deploy:
          name: Deploy
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              curl -sSL https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip -o ghr.zip
              unzip ghr.zip
              if [[ $CIRCLE_TAG = *"rc"* ]]; then
                pre=-prerelease
              fi
              ./ghr $pre -u hypriot $CIRCLE_TAG output/
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_armhf:
          filters:
            tags:
              only: /.*/
      - build_arm64:
          filters:
            tags:
              only: /.*/
